name: libutil-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: run-cmake
    - uses: lukka/run-cmake@v2.5
    - run: make build
  tests:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Unit-tests
      - run: make test
